name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build and publish (Windows)
        env:
          GH_TOKEN: ${{ secrets.SIGN_TOKEN }}
        run: |
          npm run build
          npm run build:win

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build and publish (macOS)
        env:
          GH_TOKEN: ${{ secrets.SIGN_TOKEN }}
        run: |
          npm run build
          npm run build:mac
